language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함실킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy 디렉토리 전체 파일 압
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 deploy 디렉토리 생성
  # deploy로 zip 파일 이동
  - mv before-deploy/before-deploy.zip deploy/Springboot-crud-oauth2.zip

# S3 upload or CodeDeploy로 배포 등 외부 서비스와 연동될 행위들 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: wodyweb-springboot-build # S3 bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: wodyweb-springboot-build
    key: Springboot-crud-oauth2.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: wodyweb-springboot # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: wodyweb-springboot-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - yjna.dev@gmail.com
    on_success: always
    on_failure: always